export enum UserRole {
  STUDENT = 'STUDENT',
  COMPANY = 'COMPANY',
  UNIVERSITY_DEPARTMENT = 'UNIVERSITY_DEPARTMENT',
}

export enum UserRoleBackend {
  UNVERIFIED_STUDENT = 'UNVERIFIED_STUDENT',
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN',
  DEAN = 'DEAN',
  COMPANY = 'COMPANY',
}
